/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/main/page` | `/main/page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin/page` | `/signin/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin/styles` | `/signin/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/page` | `/signup/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/styles` | `/signup/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/page` | `/profile/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/styles` | `/profile/styles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(panel)'}/main/page` | `/main/page`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signin/page` | `/signin/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signin/styles` | `/signin/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup/page` | `/signup/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup/styles` | `/signup/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(panel)'}/profile/page` | `/profile/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(panel)'}/profile/styles` | `/profile/styles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(panel)'}/main/page${`?${string}` | `#${string}` | ''}` | `/main/page${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signin/page${`?${string}` | `#${string}` | ''}` | `/signin/page${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signin/styles${`?${string}` | `#${string}` | ''}` | `/signin/styles${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup/page${`?${string}` | `#${string}` | ''}` | `/signup/page${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup/styles${`?${string}` | `#${string}` | ''}` | `/signup/styles${`?${string}` | `#${string}` | ''}` | `${'/(panel)'}/profile/page${`?${string}` | `#${string}` | ''}` | `/profile/page${`?${string}` | `#${string}` | ''}` | `${'/(panel)'}/profile/styles${`?${string}` | `#${string}` | ''}` | `/profile/styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/main/page` | `/main/page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin/page` | `/signin/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin/styles` | `/signin/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/page` | `/signup/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/styles` | `/signup/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/page` | `/profile/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(panel)'}/profile/styles` | `/profile/styles`; params?: Router.UnknownInputParams; };
    }
  }
}
